rvm:
  - 2.2.2
  - 2.3.0
  - 2.4.3
  - 2.5.0

gemfile:
  - gemfiles/Gemfile.activerecord50
  - gemfiles/Gemfile.activerecord51
  - gemfiles/Gemfile.activerecord52
  - gemfiles/Gemfile.activerecord-edge

matrix:
  exclude:
    - rvm: 2.2.2
      gemfile: gemfiles/Gemfile.activerecord-edge
    - rvm: 2.3.0
      gemfile: gemfiles/Gemfile.activerecord-edge

before_script:
  - mysql -e 'create database pedant_mysql2_test;'

sudo: false
