services:
  - mysql

rvm:
  - '2.5'
  - '2.6'
  - '2.7'

gemfile:
  - gemfiles/Gemfile.activerecord52
  - gemfiles/Gemfile.activerecord60
  - gemfiles/Gemfile.activerecord-edge

matrix:
  exclude:
    - rvm: '2.5'
      gemfile: gemfiles/Gemfile.activerecord-edge
    - rvm: '2.6'
      gemfile: gemfiles/Gemfile.activerecord-edge

before_script:
  - mysql -u root -h 127.0.0.1 -e 'create database pedant_mysql2_test;'

sudo: false
